my_dict = {
    'fruits': ['Whitesapote', 'Whitecurrant', 'Uglifruit', 'Tomato', 'Tayberry', 'Tangelo', 'Tamarind', 'Tamarillo',
               'Surinamcherry', 'Strawberry', 'Starfruit', 'Starapple', 'Soursop', 'HawthornBerry', 'ShineMuscat',
               'Salak', 'Salalberry', 'Roseapple', 'Redcurrant', 'Rambutan', 'Salmonberry', 'Raspberry', 'Quince',
               'Purplemangosteen', 'Pomelo', 'Pomegranate', 'Plumcot', 'Pineberry', 'Pineapple', 'Prune', 'Plum',
               'Plantain', 'Persimmon', 'Pear', 'Peach', 'Pawpaw', 'Passionfruit', 'Papaya', 'Tangerine', 'Mandarine',
               'Clementine', 'Bloodorange', 'Orange', 'Mulberry', 'Monsteradeliciosa', 'Miraclefruit', 'Watermelon',
               'Muskmelon', 'Mousemelon', 'Honeydew', 'Galiamelon', 'Cantaloupe', 'Melon', 'Marionberry', 'Mangosteen',
               'Mango', 'MameySapote', 'MameyApple', 'MagellanBarberry', 'Lychee', 'Loganberry', 'Lemon', 'Kumquat',
               'Kiwifruit', 'Kiwano', 'KaffirLime', 'Juniperberry', 'Jujube', 'Jostaberry', 'Japaneseplum', 'Jambul',
               'Jackfruit', 'Jabuticaba', 'Huckleberry', 'Honeyberry', 'HalaFruit', 'Guava', 'Grewiaasiatica',
               'Grapefruit', 'Raisin', 'Grape', 'Gooseberry', 'Gojiberry', 'FingerLime', 'Fig', 'Feijoa', 'Elderberry',
               'EggFruit', 'Durian', 'Dragonfruit', 'Damson', 'Currant', 'Cranberry', 'Crabapple', 'Coconut',
               'CocoDeMer', 'Cloudberry', 'Chicofruit', 'Cherry', 'Cherimoya', 'Cempedak', 'Canistel', 'Cactuspear',
               'Buddhashand', 'Breadfruit', 'Boysenberry', 'Blueberry', 'Blacksapote', 'Blackberry', 'Bilberry',
               'Banana', 'Avocado', 'Apricot', 'Apple'],
    'animals': ['Reindeer', 'Otter', 'Hedgehog', 'Mole', 'Lizard', 'Badger', 'Rat', 'Deer', 'Frog', 'Toad', 'Hare',
                'Bat', 'Gorilla', 'Fox', 'Elk', 'Hippopotamus', 'Kangaroo', 'Snake', 'Squirrel', 'Elephant', 'Dolphin',
                'Crocodile', 'Arcticwolf', 'Lion', 'Raccoon', 'Chimpanzee', 'Coyote', 'Bluewhale', 'Bear', 'Tiger',
                'Owl', 'Alligator', 'Koala', 'Starfish', 'Camel', 'Woodpecker', 'Giraffe', 'Deer', 'Sheep', 'Hedgehong',
                'Coyote', 'Fox', 'Giraffe', 'Hippopotamus', 'Leopard', 'Elephant', 'Mole', 'Koala', 'Cow', 'Monkey',
                'Horse', 'Goat', 'Kangaroo', 'Mouse', 'Otter', 'Walrus', 'Panda', 'Lion', 'Ox', 'Chimpanzee', 'Dog',
                'Squirrel'], }
